# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\DESA\UI_Frame\CreateLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateLogin(object):
    def setupUi(self, CreateLogin):
        CreateLogin.setObjectName("CreateLogin")
        CreateLogin.resize(321, 172)
        self.centralwidget = QtWidgets.QWidget(CreateLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 10, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-10, 60, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEditAccount = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAccount.setGeometry(QtCore.QRect(80, 20, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEditAccount.setFont(font)
        self.lineEditAccount.setObjectName("lineEditAccount")
        self.lineEditPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(80, 70, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.CreateUser = QtWidgets.QPushButton(self.centralwidget)
        self.CreateUser.setGeometry(QtCore.QRect(80, 120, 231, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.CreateUser.setFont(font)
        self.CreateUser.setObjectName("CreateUser")
        CreateLogin.setCentralWidget(self.centralwidget)

        self.retranslateUi(CreateLogin)
        QtCore.QMetaObject.connectSlotsByName(CreateLogin)

    def retranslateUi(self, CreateLogin):
        _translate = QtCore.QCoreApplication.translate
        CreateLogin.setWindowTitle(_translate("CreateLogin", "创建用户"))
        self.label.setText(_translate("CreateLogin", "账号"))
        self.label_2.setText(_translate("CreateLogin", "密码"))
        self.CreateUser.setText(_translate("CreateLogin", "创建用户"))
