# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\DESA\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(382, 242)
        self.AccountEdit = QtWidgets.QLineEdit(Login)
        self.AccountEdit.setGeometry(QtCore.QRect(110, 30, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.AccountEdit.setFont(font)
        self.AccountEdit.setObjectName("AccountEdit")
        self.PasswordEdit = QtWidgets.QLineEdit(Login)
        self.PasswordEdit.setGeometry(QtCore.QRect(110, 100, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.PasswordEdit.setFont(font)
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.pushButtonRegister = QtWidgets.QPushButton(Login)
        self.pushButtonRegister.setGeometry(QtCore.QRect(110, 160, 101, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRegister.setFont(font)
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.pushButtonLogin = QtWidgets.QPushButton(Login)
        self.pushButtonLogin.setGeometry(QtCore.QRect(250, 160, 101, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLogin.setFont(font)
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.layoutWidget = QtWidgets.QWidget(Login)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 131, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.pushButtonRegister.setText(_translate("Login", "注册"))
        self.pushButtonLogin.setText(_translate("Login", "登录"))
        self.label.setText(_translate("Login", "账号"))
        self.label_2.setText(_translate("Login", "密码"))
